name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build for production
        run: npm run build
      - name: Stop the server
        run: pm2 stop things_frontend 2> /dev/null || true
      - name: Start the server
        run: pm2 start build/index.js --name things_frontend
      - name: Save pm2 process
        run: pm2 save